import type { CanonicalConcept } from "../types.ts";
import {
  PHYSICAL_TYPES,
  LOGICAL_TYPES,
  BUSINESS_ROLES,
  SEMANTIC_NATURES,
  GRAIN_LEVELS,
  AGGREGATION_TYPES,
} from "../types.ts";

export const MARKETING_CONCEPTS: Record<string, CanonicalConcept> = {
  // ── DÉPENSES MARKETING / AD SPEND ──
  "marketing.spend.ads": {
    conceptId: "marketing.spend.ads",
    canonicalName: "ad_spend",
    domain: "marketing",
    subdomain: "advertising",
    nature: SEMANTIC_NATURES.FINANCIAL_MEASURE,
    businessRole: BUSINESS_ROLES.FLOW,
    physicalType: PHYSICAL_TYPES.DECIMAL,
    logicalType: LOGICAL_TYPES.CURRENCY,
    unit: "currency",
    grain: GRAIN_LEVELS.CAMPAIGN,
    temporalType: "flow",
    synonyms: {
      fr: [
        "depenses publicitaires", "depense pub", "budget depense", "frais publicitaires",
        "ad spend", "cout de campagne", "montant investi", "cout publicitaire", "depenses marketing"
      ],
      en: [
        "ad spend", "advertising spend", "media spend", "campaign spend", "marketing spend",
        "spend", "ad cost", "marketing cost", "advertising cost"
      ],
      es: ["gasto publicitario", "gasto en publicidad", "inversion publicitaria"],
      pt: ["gasto com publicidade", "investimento publicitario"],
      de: ["werbeausgaben", "werbekosten", "media spend"],
      it: ["spesa pubblicitaria", "costo pubblicitario"],
      nl: ["advertentiekosten", "marketinguitgaven"],
    },
    abbreviations: ["SPEND", "AD SPEND"],
    allowedAggregations: [AGGREGATION_TYPES.SUM, AGGREGATION_TYPES.AVG],
    entityBindings: [
      { entity: "Campaign", field: "budget_spent", isDefault: true },
      { entity: "CampaignDaily", field: "spend" },
    ],
  },

  // ── IMPRESSIONS ──
  "marketing.metrics.impressions": {
    conceptId: "marketing.metrics.impressions",
    canonicalName: "impressions",
    domain: "marketing",
    subdomain: "metrics",
    nature: SEMANTIC_NATURES.QUANTITY_MEASURE,
    businessRole: BUSINESS_ROLES.COUNT,
    physicalType: PHYSICAL_TYPES.INTEGER,
    logicalType: LOGICAL_TYPES.QUANTITY,
    unit: "units",
    grain: GRAIN_LEVELS.CAMPAIGN,
    temporalType: "flow",
    synonyms: {
      fr: ["impressions", "nombre d'impressions", "vues publicitaires", "affichages"],
      en: ["impressions", "views", "ad impressions", "impr"],
      es: ["impresiones", "visualizaciones"],
      pt: ["impressoes", "visualizacoes"],
      de: ["einblendungen", "impressions", "sichtkontakte"],
      it: ["impressioni", "visualizzazioni"],
      nl: ["vertoningen", "impressies"],
    },
    abbreviations: ["IMPR", "VIEWS"],
    allowedAggregations: [AGGREGATION_TYPES.SUM, AGGREGATION_TYPES.AVG],
    entityBindings: [
      { entity: "Campaign", field: "impressions", isDefault: true },
      { entity: "CampaignDaily", field: "impressions" },
    ],
  },

  // ── CLICS ──
  "marketing.metrics.clicks": {
    conceptId: "marketing.metrics.clicks",
    canonicalName: "clicks",
    domain: "marketing",
    subdomain: "metrics",
    nature: SEMANTIC_NATURES.QUANTITY_MEASURE,
    businessRole: BUSINESS_ROLES.COUNT,
    physicalType: PHYSICAL_TYPES.INTEGER,
    logicalType: LOGICAL_TYPES.QUANTITY,
    unit: "units",
    grain: GRAIN_LEVELS.CAMPAIGN,
    temporalType: "flow",
    synonyms: {
      fr: ["clics", "nombre de clics", "clics sur lien", "clics publicitaires"],
      en: ["clicks", "link clicks", "ad clicks", "click count"],
      es: ["clics", "clics en el enlace"],
      pt: ["cliques", "cliques no link"],
      de: ["klicks", "link-klicks"],
      it: ["clic", "clic sul link"],
      nl: ["klikken", "linkklikken"],
    },
    abbreviations: ["CLICKS", "CLK"],
    allowedAggregations: [AGGREGATION_TYPES.SUM, AGGREGATION_TYPES.AVG],
    entityBindings: [
      { entity: "Campaign", field: "clicks", isDefault: true },
      { entity: "CampaignDaily", field: "clicks" },
    ],
  },

  // ── TAUX DE CLIC (CTR) ──
  "marketing.metrics.ctr": {
    conceptId: "marketing.metrics.ctr",
    canonicalName: "ctr",
    domain: "marketing",
    subdomain: "metrics",
    nature: SEMANTIC_NATURES.PERCENTAGE_MEASURE,
    businessRole: BUSINESS_ROLES.RATE,
    physicalType: PHYSICAL_TYPES.FLOAT,
    logicalType: LOGICAL_TYPES.PERCENTAGE,
    unit: "%",
    grain: GRAIN_LEVELS.CAMPAIGN,
    temporalType: "flow",
    synonyms: {
      fr: ["taux de clic", "ctr", "taux de clics", "pourcentage de clics"],
      en: ["ctr", "click through rate", "click-through rate", "click rate"],
      es: ["ctr", "porcentaje de clics"],
      pt: ["ctr", "taxa de cliques"],
      de: ["klickrate", "ctr", "durchklickrate"],
      it: ["ctr", "percentuale di clic"],
      nl: ["doorklikratio", "ctr"],
    },
    abbreviations: ["CTR"],
    derivedFormula: "clicks / impressions",
    allowedAggregations: [AGGREGATION_TYPES.AVG],
    forbiddenOperations: ["SUM"],
    entityBindings: [
      { entity: "Campaign", field: "ctr", isDefault: true },
    ],
  },

  // ── COÛT PAR CLIC (CPC) ──
  "marketing.metrics.cpc": {
    conceptId: "marketing.metrics.cpc",
    canonicalName: "cpc",
    domain: "marketing",
    subdomain: "metrics",
    nature: SEMANTIC_NATURES.FINANCIAL_MEASURE,
    businessRole: BUSINESS_ROLES.RATE,
    physicalType: PHYSICAL_TYPES.DECIMAL,
    logicalType: LOGICAL_TYPES.CURRENCY,
    unit: "currency",
    grain: GRAIN_LEVELS.CAMPAIGN,
    temporalType: "flow",
    synonyms: {
      fr: ["cpc", "cout par clic", "cout unitaire par clic"],
      en: ["cpc", "cost per click", "average cost per click", "avg cpc"],
      es: ["cpc", "coste por clic"],
      pt: ["cpc", "custo por clique"],
      de: ["cpc", "kosten pro klick"],
      it: ["cpc", "costo per clic"],
      nl: ["cpc", "kosten per klik"],
    },
    abbreviations: ["CPC"],
    derivedFormula: "ad_spend / clicks",
    allowedAggregations: [AGGREGATION_TYPES.AVG],
    forbiddenOperations: ["SUM"],
    entityBindings: [
      { entity: "Campaign", field: "cpc", isDefault: true },
    ],
  },

  // ── RETOUR SUR DÉPENSES PUBLICITAIRES (ROAS) ──
  "marketing.metrics.roas": {
    conceptId: "marketing.metrics.roas",
    canonicalName: "roas",
    domain: "marketing",
    subdomain: "metrics",
    nature: SEMANTIC_NATURES.RATIO_MEASURE,
    businessRole: BUSINESS_ROLES.RATIO,
    physicalType: PHYSICAL_TYPES.FLOAT,
    logicalType: LOGICAL_TYPES.RATING,
    unit: "ratio",
    grain: GRAIN_LEVELS.CAMPAIGN,
    temporalType: "flow",
    synonyms: {
      fr: ["roas", "retour sur depense publicitaire", "rendement publicitaire", "ratio roas"],
      en: ["roas", "return on ad spend", "return on advertising spend"],
      es: ["roas", "retorno de la inversion publicitaria"],
      pt: ["roas", "retorno sobre investimento publicitario"],
      de: ["roas", "kurzfristiger werbeerfolg"],
      it: ["roas", "ritorno sulla spesa pubblicitaria"],
      nl: ["roas", "rendement op advertentie-uitgaven"],
    },
    abbreviations: ["ROAS"],
    derivedFormula: "revenue / ad_spend",
    allowedAggregations: [AGGREGATION_TYPES.AVG],
    forbiddenOperations: ["SUM"],
    entityBindings: [
      { entity: "Campaign", field: "roas", isDefault: true },
    ],
  },

  // ── COÛT D'ACQUISITION CLIENT (CAC) ──
  "marketing.metrics.cac": {
    conceptId: "marketing.metrics.cac",
    canonicalName: "cac",
    domain: "marketing",
    subdomain: "metrics",
    nature: SEMANTIC_NATURES.FINANCIAL_MEASURE,
    businessRole: BUSINESS_ROLES.RATE,
    physicalType: PHYSICAL_TYPES.DECIMAL,
    logicalType: LOGICAL_TYPES.CURRENCY,
    unit: "currency",
    grain: GRAIN_LEVELS.MONTH,
    temporalType: "flow",
    synonyms: {
      fr: ["cac", "cout d'acquisition client", "cout d'acquisition", "cout par nouveau client"],
      en: ["cac", "customer acquisition cost", "acquisition cost", "cost to acquire a customer"],
      es: ["cac", "coste de adquisicion de clientes"],
      pt: ["cac", "custo de aquisicao de clientes"],
      de: ["cac", "kundenakquisitionskosten"],
      it: ["cac", "costo di acquisizione clienti"],
      nl: ["cac", "klantacquisitiekosten"],
    },
    abbreviations: ["CAC"],
    derivedFormula: "marketing_spend / new_customers",
    allowedAggregations: [AGGREGATION_TYPES.AVG],
    forbiddenOperations: ["SUM"],
    entityBindings: [],
  },
};
