// GESCOP — Registre unique de concepts (spec v2, section 3)
//
// Portée de ce fichier : le lexique utilisé pour RECONNAÎTRE une colonne à
// l'import (en-tête -> concept métier) et pour TRADUIRE une valeur de canal
// marketing (ex. "Facebook Ads" -> meta_ads). Ce n'est PAS un remplacement du
// catalogue riche `src/lib/core/semanticTypes.js` (SEMANTIC_TYPES), qui reste
// la source pour la compatibilité d'affichage/agrégation des KPI — les deux
// catalogues seront réconciliés dans un chantier ultérieur une fois que ce
// registre aura fait ses preuves sur la reconnaissance de colonnes.
//
// Ce fichier ne doit contenir aucune syntaxe spécifique à Deno ou à un
// bundler : il est importé tel quel depuis base44/shared (Deno) et depuis
// src/lib/core (Vite).

export type Criticality = "core" | "optional";
export type MissingBehavior = "NOT_IMPORTED" | "QUARANTINED" | "ZERO_IS_VALID";

export const ECONOMIC_ROLES = Object.freeze({
  FLOW: "FLOW",
  STOCK: "STOCK",
  RATE: "RATE",
  RATIO: "RATIO",
  COUNT: "COUNT",
});

export const DATA_TYPES = Object.freeze({
  CURRENCY: "currency",
  PERCENTAGE: "percentage",
  NUMBER: "number",
  INTEGER: "integer",
  DATE: "date",
  STRING: "string",
});

export const AGGREGATION_METHODS = Object.freeze({
  SUM: "sum",
  AVG: "avg",
  LAST: "last",
  COUNT: "count",
  NONE: "none",
});

export const DOMAINS = Object.freeze({
  FINANCE: "finance",
  VENTES: "ventes",
  MARKETING: "marketing",
  OPERATIONS: "operations",
  RH: "rh",
  TRESORERIE: "tresorerie",
  CLIENTS: "clients",
});

export interface ConceptDefinition {
  conceptId: string; // "finance.revenue" — compatible avec semanticMatcher.matchConcept
  canonicalKey: string; // "revenue" — compatible avec FIELD_ALIASES / kpiRegistry deps
  kind: keyof typeof ECONOMIC_ROLES;
  criticality: Criticality;
  domains: Array<keyof typeof DOMAINS>;
  dataType: keyof typeof DATA_TYPES;
  aggregation: keyof typeof AGGREGATION_METHODS;
  // Synonymes normalisés (accents retirés, minuscules, espaces simples) pour
  // reconnaître un EN-TÊTE de colonne comme ce concept.
  lexicon: string[];
  missingBehavior: MissingBehavior;
  // Synonymes qui ne doivent JAMAIS résoudre vers ce concept (garde-fou d'ambiguïté).
  forbidden?: string[];
  label: { fr: string; en: string };
}

export interface CategoryDefinition {
  categoryId: string;
  canonicalValues: string[];
  // Valeur canonique -> synonymes de VALEUR DE CELLULE (pas d'en-tête de colonne).
  lexicon: Record<string, string[]>;
}

export const REGISTRY_VERSION = "2026-09-22.1";

export const CONCEPTS: Record<string, ConceptDefinition> = {
  "temporal.date": {
    conceptId: "temporal.date",
    canonicalKey: "date",
    kind: "COUNT",
    criticality: "core",
    domains: ["FINANCE", "VENTES", "OPERATIONS"],
    dataType: "DATE",
    aggregation: "NONE",
    // "periode" est volontairement exclu : ALIAS_CANONIQUES le mappe deja a
    // "period" (distinct de "date"), et ce chantier n'ecrase pas les
    // resolutions ambigues existantes sans revue dediee.
    lexicon: ["date", "mois", "annee", "timestamp", "created_at", "date_operation", "date de commande"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Date", en: "Date" },
  },
  "finance.revenue": {
    conceptId: "finance.revenue",
    canonicalKey: "revenue",
    kind: "FLOW",
    criticality: "core",
    domains: ["FINANCE", "VENTES"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    // "chiffre affaires" (sans "d") est volontairement exclu : ALIAS_CANONIQUES
    // a deja deux entrees contradictoires pour cette cle exacte (revenue et
    // total_revenue, un doublon de cle preexistant dans ce fichier) — pas a ce
    // chantier de trancher laquelle est correcte. "chiffre d affaires" (avec
    // "d") est une cle distincte, non ambigue, et reste dans ce lexique.
    lexicon: [
      "ca", "chiffre d affaires", "revenu", "revenue", "revenus",
      "ventes", "vente", "sales", "sales revenue", "turnover", "montant des ventes",
    ],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Chiffre d'affaires", en: "Revenue" },
  },
  "finance.cogs": {
    conceptId: "finance.cogs",
    canonicalKey: "cogs",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["cout des biens vendus", "cout des marchandises vendues", "cost of goods sold", "cogs"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Coût des marchandises vendues", en: "Cost of goods sold" },
  },
  "finance.grossMargin": {
    conceptId: "finance.grossMargin",
    canonicalKey: "gross_margin",
    kind: "RATE",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "PERCENTAGE",
    aggregation: "AVG",
    // "profit brut"/"gross profit" est volontairement EXCLU de ce lexique :
    // c'est un montant en dollars, pas un taux, et le concept juste en
    // dessous (finance.grossProfit) le couvre. Sans cette séparation, une
    // colonne "Profit Brut ($)" et une colonne "Marge Brute %" résolvaient
    // toutes deux vers gross_margin ; le dédoublonnage anti-écrasement
    // (importPlan.ts) devait alors arbitrer et laissait "Marge Brute %" sans
    // champ, alors que Order/Product ont bien deux champs distincts
    // (gross_profit $ et gross_margin %).
    lexicon: ["marge brute", "marge", "gross margin", "gross profit margin", "taux de marge brute", "marge %", "% marge"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Marge brute", en: "Gross margin" },
  },
  "finance.grossProfit": {
    conceptId: "finance.grossProfit",
    canonicalKey: "gross_profit",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE", "VENTES"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["profit brut", "profit", "gross profit", "benefice brut", "resultat brut", "marge brute en dollars"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Profit brut", en: "Gross profit" },
  },
  "finance.expense": {
    conceptId: "finance.expense",
    canonicalKey: "expense",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    // "depense totale" est volontairement exclu : ALIAS_CANONIQUES le mappe
    // deja (vraisemblablement a tort) a "total_revenue" — pas a ce chantier
    // de corriger cette resolution existante sans revue dediee.
    lexicon: ["depense", "depenses", "expense", "expenses"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Dépense", en: "Expense" },
  },
  "finance.cashBalance": {
    conceptId: "finance.cashBalance",
    canonicalKey: "closing_cash",
    kind: "STOCK",
    criticality: "optional",
    domains: ["TRESORERIE"],
    dataType: "CURRENCY",
    aggregation: "LAST",
    lexicon: ["solde cloture", "solde final", "solde banque", "solde bancaire", "solde", "closing cash", "cash balance"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Solde de trésorerie", en: "Cash balance" },
  },
  // marketing.spend est LE concept au cœur du bug "Facebook Ads ignoré" :
  // aucune des tables existantes (CONCEPT_MAPPINGS, FIELD_ALIASES) n'avait de
  // synonyme d'EN-TÊTE pour un canal publicitaire (ENUM_TRANSLATIONS ne
  // traduit ces mots que comme VALEUR de cellule d'une colonne "channel" déjà
  // reconnue — jamais comme nom de colonne). Ce lexique comble ce trou.
  "marketing.spend": {
    conceptId: "marketing.spend",
    canonicalKey: "advertising_spend",
    kind: "FLOW",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: [
      "depenses publicitaires", "cout publicite", "ad spend", "advertising spend", "advertising cost",
      // en-têtes de fichiers larges "1 colonne par canal" — la cause racine du bug :
      "facebook ads", "facebook", "fb ads", "fb", "meta ads", "meta",
      "google ads", "adwords", "tiktok ads", "instagram ads",
    ],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Dépenses publicitaires", en: "Advertising spend" },
  },
  "marketing.ctr": {
    conceptId: "marketing.ctr",
    canonicalKey: "ctr",
    kind: "RATE",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "PERCENTAGE",
    aggregation: "AVG",
    lexicon: ["taux de clic", "taux clic", "click through rate", "click rate", "ctr"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Taux de clic", en: "Click-through rate" },
  },
  "marketing.cpc": {
    conceptId: "marketing.cpc",
    canonicalKey: "cpc",
    kind: "RATE",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "CURRENCY",
    aggregation: "AVG",
    lexicon: ["cout par clic", "cout clic", "cout/clic", "cout_clic", "cout_par_clic", "cost per click", "cpc", "c.p.c."],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Coût par clic", en: "Cost per click" },
  },
  "marketing.cpa": {
    conceptId: "marketing.cpa",
    canonicalKey: "cpa",
    kind: "RATE",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "CURRENCY",
    aggregation: "AVG",
    lexicon: ["cout par acquisition", "cout par conversion", "cost per acquisition", "cpa"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Coût par acquisition", en: "Cost per acquisition" },
  },
  "marketing.roas": {
    conceptId: "marketing.roas",
    canonicalKey: "roas",
    kind: "RATIO",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "NUMBER",
    aggregation: "AVG",
    lexicon: ["retour sur depenses publicitaires", "rendement publicitaire", "return on ad spend", "roas"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Retour sur dépenses publicitaires", en: "Return on ad spend" },
  },
  "marketing.campaign_revenue": {
    conceptId: "marketing.campaign_revenue",
    canonicalKey: "campaign_revenue",
    kind: "FLOW",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: [
      "revenu campagne", "revenu des campagnes", "revenus campagnes", "revenu publicite",
      "campaign revenue", "attributed revenue", "revenu attribue", "ca campagne",
    ],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Revenu des campagnes", en: "Campaign revenue" },
  },
  "customer.count": {
    conceptId: "customer.count",
    canonicalKey: "customer_count",
    kind: "COUNT",
    criticality: "optional",
    domains: ["CLIENTS"],
    dataType: "INTEGER",
    aggregation: "SUM",
    lexicon: ["clients", "acheteurs", "customers", "nb clients", "nombre de clients"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Nombre de clients", en: "Customer count" },
  },
  "customer.id": {
    conceptId: "customer.id",
    canonicalKey: "customer_id",
    kind: "COUNT",
    criticality: "optional",
    domains: ["CLIENTS"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["client_id", "id_client", "customer_id"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Identifiant client", en: "Customer ID" },
  },
  "qualitative.feedback": {
    conceptId: "qualitative.feedback",
    canonicalKey: "feedback",
    kind: "COUNT",
    criticality: "optional",
    domains: ["CLIENTS"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["commentaire", "avis", "feedback", "review", "remarque"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Commentaire", en: "Feedback" },
  },

  // ── Ajouts du 22 sept 2026 ────────────────────────────────────────────────
  // Concepts de mesure des entites importees. Regles d'ajout, verifiees par
  // un audit avant ecriture :
  //  - canonicalKey = un VRAI champ d'entite, pour que ces synonymes, fusionnes
  //    dans ALIAS_CANONIQUES (et prioritaires sur les alias ecrits a la main),
  //    rattachent une colonne a un champ qui existe ;
  //  - un synonyme n'est retenu que s'il ne resolvait vers rien a l'import, ou
  //    deja vers ce meme champ. 22 synonymes ecartes pour cette raison (ex.
  //    « quantity » -> sales_quantity, « tps » -> tax_amount, « clv » ->
  //    customer_lifetime_value) : les changer relevait d'une autre decision.
  "sales.quantity": {
    conceptId: "sales.quantity",
    canonicalKey: "quantity",
    kind: "COUNT",
    criticality: "optional",
    domains: ["VENTES"],
    dataType: "INTEGER",
    aggregation: "SUM",
    lexicon: ["quantite","quantite vendue","qte","qte vendue","qty","quantity sold","nombre d articles","nb articles"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Quantité vendue", en: "Quantity" },
  },
  "sales.unitPrice": {
    conceptId: "sales.unitPrice",
    canonicalKey: "unit_price",
    kind: "RATE",
    criticality: "optional",
    domains: ["VENTES"],
    dataType: "CURRENCY",
    aggregation: "AVG",
    lexicon: ["prix unitaire","pu","prix de vente unitaire","prix unitaire de vente","unit price","selling price per unit"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Prix unitaire", en: "Unit price" },
  },
  "finance.unitCost": {
    conceptId: "finance.unitCost",
    canonicalKey: "unit_cost",
    kind: "RATE",
    criticality: "optional",
    domains: ["VENTES"],
    dataType: "CURRENCY",
    aggregation: "AVG",
    lexicon: ["cout unitaire","cout d achat unitaire","cout de revient unitaire","unit cost","cost per unit"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Coût unitaire", en: "Unit cost" },
  },
  "sales.discount": {
    conceptId: "sales.discount",
    canonicalKey: "discount",
    kind: "FLOW",
    criticality: "optional",
    domains: ["VENTES"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    // Montant de remise ; un TAUX de remise (« taux remise », « % ») n'est pas ce concept.
    lexicon: ["remise","rabais","escompte","discount","remise ligne","rabais accorde","reduction"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Remise", en: "Discount" },
  },
  "sales.tax": {
    conceptId: "sales.tax",
    canonicalKey: "tax",
    kind: "FLOW",
    criticality: "optional",
    domains: ["VENTES","FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["taxe","tvh","tax","sales tax","montant taxes","montant des taxes"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Taxes", en: "Tax" },
  },
  // Nouveaux concepts fiscaux, paie et ESG
  "finance.tps": {
    conceptId: "finance.tps",
    canonicalKey: "tax_federal",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["tps", "gst", "taxe federale", "tps a verser", "tps perçue"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "TPS", en: "GST" },
  },
  "finance.tvq": {
    conceptId: "finance.tvq",
    canonicalKey: "tax_provincial",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["tvq", "qst", "tvh", "hst", "taxe provinciale", "tvq a verser", "tvq perçue"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "TVQ", en: "QST" },
  },
  "finance.dpa": {
    conceptId: "finance.dpa",
    canonicalKey: "dpa_rate",
    kind: "RATE",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "PERCENTAGE",
    aggregation: "NONE",
    lexicon: ["taux dpa", "dpa", "amortissement", "taux amortissement"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Taux DPA", en: "DPA Rate" },
  },
  "rh.rrq": {
    conceptId: "rh.rrq",
    canonicalKey: "employer_rrq",
    kind: "FLOW",
    criticality: "optional",
    domains: ["RH"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["rrq", "regie des rentes", "qpp"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "RRQ", en: "QPP" },
  },
  "rh.rqap": {
    conceptId: "rh.rqap",
    canonicalKey: "employer_rqap",
    kind: "FLOW",
    criticality: "optional",
    domains: ["RH"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["rqap", "assurance parentale"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "RQAP", en: "RQAP" },
  },
  "rh.cnesst": {
    conceptId: "rh.cnesst",
    canonicalKey: "employer_cnesst",
    kind: "FLOW",
    criticality: "optional",
    domains: ["RH"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["cnesst", "csst", "accident travail"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "CNESST", en: "CNESST" },
  },
  "rh.fss": {
    conceptId: "rh.fss",
    canonicalKey: "employer_fss",
    kind: "FLOW",
    criticality: "optional",
    domains: ["RH"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["fss", "fonds services de sante"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "FSS", en: "FSS" },
  },
  "rh.seniority": {
    conceptId: "rh.seniority",
    canonicalKey: "seniority_years",
    kind: "COUNT",
    criticality: "optional",
    domains: ["RH"],
    dataType: "NUMBER",
    aggregation: "AVG",
    lexicon: ["anciennete ans", "anciennete", "annees anciennete", "seniority", "years of service"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Ancienneté", en: "Seniority" },
  },
  "rh.total_charges": {
    conceptId: "rh.total_charges",
    canonicalKey: "total_social_charges",
    kind: "FLOW",
    criticality: "optional",
    domains: ["RH", "FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["total charges sociales cad", "total charges sociales", "charges patronales", "charges sociales"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Total charges sociales", en: "Total social charges" },
  },
  "rh.total_employer_cost": {
    conceptId: "rh.total_employer_cost",
    canonicalKey: "total_employer_cost",
    kind: "FLOW",
    criticality: "optional",
    domains: ["RH", "FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["cout global employeur cad", "cout global employeur", "cout total employeur", "total employer cost"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Coût global employeur", en: "Total employer cost" },
  },
  "rh.commission": {
    conceptId: "rh.commission",
    canonicalKey: "commission_rate",
    kind: "RATE",
    criticality: "optional",
    domains: ["RH", "VENTES"],
    dataType: "PERCENTAGE",
    aggregation: "AVG",
    lexicon: ["taux commission", "commission", "commission rate", "% commission"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Taux de commission", en: "Commission rate" },
  },
  "tax.federal": {
    conceptId: "tax.federal",
    canonicalKey: "tax_federal",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE", "VENTES"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["taxe federale tps", "tps", "taxe federale", "gst", "federal tax", "tps a verser", "tps percue"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Taxe fédérale (TPS)", en: "Federal Tax (GST)" },
  },
  "tax.provincial": {
    conceptId: "tax.provincial",
    canonicalKey: "tax_provincial",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE", "VENTES"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["taxe provinciale tvq tvh", "tvq", "tvh", "tvp", "taxe provinciale", "qst", "hst", "pst", "provincial tax", "tvq a verser", "tvq percue"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Taxe provinciale (TVQ/TVH)", en: "Provincial Tax (QST/HST)" },
  },
  "tax.total": {
    conceptId: "tax.total",
    canonicalKey: "tax",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE", "VENTES"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["montant taxes total", "montant taxes", "total taxes", "total taxes cad", "tax", "taxes"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Total des taxes", en: "Total taxes" },
  },
  "finance.subtotal": {
    conceptId: "finance.subtotal",
    canonicalKey: "subtotal",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE", "VENTES"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["sous total ht", "sous total", "subtotal", "montant ht", "total ht", "net ht", "sous-total"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Sous-total HT", en: "Subtotal" },
  },
  "finance.price": {
    conceptId: "finance.price",
    canonicalKey: "price",
    kind: "FLOW",
    criticality: "optional",
    domains: ["VENTES", "FINANCE"],
    dataType: "CURRENCY",
    aggregation: "NONE",
    lexicon: ["prix brut", "gross price", "prix regulier", "prix catalogue"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Prix unitaire brut", en: "Gross unit price" },
  },
  "finance.total": {
    conceptId: "finance.total",
    canonicalKey: "total",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE", "VENTES"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["total ttc cad", "total ttc", "montant total ttc", "total commande", "grand total", "total facture"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Total TTC", en: "Total (inc. tax)" },
  },
  "inventory.available": {
    conceptId: "inventory.available",
    canonicalKey: "available_qty",
    kind: "STOCK",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "NUMBER",
    aggregation: "SUM",
    lexicon: ["quantite disponible", "qte disponible", "stock disponible", "disponible", "available quantity"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Quantité disponible", en: "Available quantity" },
  },
  "inventory.reserved": {
    conceptId: "inventory.reserved",
    canonicalKey: "reserved_qty",
    kind: "STOCK",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "NUMBER",
    aggregation: "SUM",
    lexicon: ["quantite reservee", "qte reservee", "stock reserve", "reserve", "reserved quantity"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Quantité réservée", en: "Reserved quantity" },
  },
  "inventory.in_transit": {
    conceptId: "inventory.in_transit",
    canonicalKey: "in_transit_qty",
    kind: "STOCK",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "NUMBER",
    aggregation: "SUM",
    lexicon: ["quantite en transit", "qte en transit", "en transit", "in transit"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Quantité en transit", en: "In-transit quantity" },
  },
  "inventory.reorder_qty": {
    conceptId: "inventory.reorder_qty",
    canonicalKey: "reorder_qty_eoq",
    kind: "COUNT",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "NUMBER",
    aggregation: "NONE",
    lexicon: ["quantite reappro optimale eoq", "quantite de reapprovisionnement", "eoq", "qte reappro", "qte optimale"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Quantité réappro optimale (EOQ)", en: "Optimal Reorder Quantity (EOQ)" },
  },
  "asset.net_book_value": {
    conceptId: "asset.net_book_value",
    canonicalKey: "net_book_value",
    kind: "STOCK",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["valeur nette comptable cad", "valeur nette comptable", "vnc", "net book value", "nbv"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Valeur nette comptable", en: "Net book value" },
  },
  "asset.initial_cost": {
    conceptId: "asset.initial_cost",
    canonicalKey: "initial_cost",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["cout acquisition initial cad", "cout acquisition initial", "cout initial", "initial cost", "acquisition cost"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Coût d'acquisition initial", en: "Initial acquisition cost" },
  },
  "asset.accumulated_depreciation": {
    conceptId: "asset.accumulated_depreciation",
    canonicalKey: "accumulated_depreciation",
    kind: "FLOW",
    criticality: "optional",
    domains: ["FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["amortissement cumule cad", "amortissement cumule", "accumulated depreciation", "depreciation cumulee"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Amortissement cumulé", en: "Accumulated depreciation" },
  },
  "customer.tax_exemption": {
    conceptId: "customer.tax_exemption",
    canonicalKey: "tax_exemption_number",
    kind: "COUNT",
    criticality: "optional",
    domains: ["CLIENTS", "FINANCE"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["numero exemption taxe", "exemption taxe", "tax exemption number", "no exemption"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Numéro d'exemption de taxe", en: "Tax exemption number" },
  },
  "customer.credit_limit": {
    conceptId: "customer.credit_limit",
    canonicalKey: "credit_limit",
    kind: "STOCK",
    criticality: "optional",
    domains: ["CLIENTS", "FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["limite credit cad", "limite de credit", "credit limit", "plafond credit"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Limite de crédit", en: "Credit limit" },
  },
  "customer.loyalty_points": {
    conceptId: "customer.loyalty_points",
    canonicalKey: "loyalty_points",
    kind: "STOCK",
    criticality: "optional",
    domains: ["CLIENTS"],
    dataType: "NUMBER",
    aggregation: "SUM",
    lexicon: ["solde points fidelite", "points fidelite", "loyalty points", "solde points"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Points de fidélité", en: "Loyalty points" },
  },
  "supplier.neq": {
    conceptId: "supplier.neq",
    canonicalKey: "neq_number",
    kind: "COUNT",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["neq quebec", "neq", "numero entreprise quebec"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "NEQ Québec", en: "NEQ Quebec" },
  },
  "supplier.gst_number": {
    conceptId: "supplier.gst_number",
    canonicalKey: "gst_number",
    kind: "COUNT",
    criticality: "optional",
    domains: ["OPERATIONS", "FINANCE"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["numero tps tvh", "numero tps", "no tps", "gst number"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Numéro TPS/TVH", en: "GST/HST number" },
  },
  "supplier.qst_number": {
    conceptId: "supplier.qst_number",
    canonicalKey: "qst_number",
    kind: "COUNT",
    criticality: "optional",
    domains: ["OPERATIONS", "FINANCE"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["numero tvq", "no tvq", "qst number"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Numéro TVQ", en: "QST number" },
  },
  "esg.score": {
    conceptId: "esg.score",
    canonicalKey: "esg_score",
    kind: "COUNT",
    criticality: "optional",
    domains: ["OPERATIONS", "FINANCE"],
    dataType: "NUMBER",
    aggregation: "AVG",
    lexicon: ["esg", "score esg", "esg score", "score rse esg", "impact environnemental"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Score ESG", en: "ESG Score" },
  },
  "customer.name": {
    conceptId: "customer.name",
    canonicalKey: "full_name",
    kind: "COUNT",
    criticality: "optional",
    domains: ["CLIENTS"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["nom complet", "nom du client", "nom client", "client", "full name", "nom et prenom", "nom prenom", "nom_complet"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Nom complet du client", en: "Customer full name" },
  },
  "customer.postal_code": {
    conceptId: "customer.postal_code",
    canonicalKey: "postal_code",
    kind: "COUNT",
    criticality: "optional",
    domains: ["CLIENTS"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["code postal", "code postale", "postal code", "zip code", "zip", "code_postal"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Code postal", en: "Postal code" },
  },
  "supplier.contact_name": {
    conceptId: "supplier.contact_name",
    canonicalKey: "contact_name",
    kind: "COUNT",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["contact principal", "contact", "nom du contact", "contact name", "personne ressource", "contact_principal"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Contact principal", en: "Primary contact" },
  },
  "supplier.payment_terms": {
    conceptId: "supplier.payment_terms",
    canonicalKey: "payment_terms",
    kind: "COUNT",
    criticality: "optional",
    domains: ["OPERATIONS", "FINANCE"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["conditions paiement", "conditions de paiement", "modalites de paiement", "termes de paiement", "termes paiement", "payment terms", "conditions_paiement"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Conditions de paiement", en: "Payment terms" },
  },
  "inventory.closingStock": {
    conceptId: "inventory.closingStock",
    canonicalKey: "closing_stock",
    kind: "STOCK",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "INTEGER",
    aggregation: "LAST",
    lexicon: ["stock final","stock de cloture","stock cloture","stock actuel","closing stock","on hand","stock physique"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Stock final", en: "Closing stock" },
  },
  "inventory.openingStock": {
    conceptId: "inventory.openingStock",
    canonicalKey: "opening_stock",
    kind: "STOCK",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "INTEGER",
    aggregation: "LAST",
    lexicon: ["stock initial","stock d ouverture","stock ouverture","stock de debut","opening stock"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Stock initial", en: "Opening stock" },
  },
  "inventory.value": {
    conceptId: "inventory.value",
    canonicalKey: "inventory_value",
    kind: "STOCK",
    criticality: "optional",
    domains: ["OPERATIONS","FINANCE"],
    dataType: "CURRENCY",
    aggregation: "LAST",
    lexicon: ["valeur du stock","valeur stock","valeur d inventaire","valeur inventaire","inventory value","stock value"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Valeur du stock", en: "Inventory value" },
  },
  "inventory.unitsSold": {
    conceptId: "inventory.unitsSold",
    canonicalKey: "units_sold",
    kind: "FLOW",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "INTEGER",
    aggregation: "SUM",
    lexicon: ["sorties de stock"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Unités vendues", en: "Units sold" },
  },
  "inventory.purchases": {
    conceptId: "inventory.purchases",
    canonicalKey: "purchases",
    kind: "FLOW",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "INTEGER",
    aggregation: "SUM",
    lexicon: ["entrees de stock","receptions"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Entrées de stock", en: "Stock purchases" },
  },
  "treasury.cashIn": {
    conceptId: "treasury.cashIn",
    canonicalKey: "cash_in",
    kind: "FLOW",
    criticality: "optional",
    domains: ["TRESORERIE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["encaissements","encaissement","entrees de tresorerie","cash in","inflows","cash inflows"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Encaissements", en: "Cash in" },
  },
  "treasury.cashOut": {
    conceptId: "treasury.cashOut",
    canonicalKey: "cash_out",
    kind: "FLOW",
    criticality: "optional",
    domains: ["TRESORERIE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["decaissements","decaissement","sorties de tresorerie","cash out","outflows","cash outflows"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Décaissements", en: "Cash out" },
  },
  "treasury.netCashFlow": {
    conceptId: "treasury.netCashFlow",
    canonicalKey: "net_cash_flow",
    kind: "FLOW",
    criticality: "optional",
    domains: ["TRESORERIE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["flux net","flux de tresorerie net","tresorerie nette du mois","net cashflow"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Flux de trésorerie net", en: "Net cash flow" },
  },
  "marketing.clicks": {
    conceptId: "marketing.clicks",
    canonicalKey: "clicks",
    kind: "COUNT",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "INTEGER",
    aggregation: "SUM",
    lexicon: ["clics","clicks","nombre de clics","nb clics"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Clics", en: "Clicks" },
  },
  "marketing.impressions": {
    conceptId: "marketing.impressions",
    canonicalKey: "impressions",
    kind: "COUNT",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "INTEGER",
    aggregation: "SUM",
    lexicon: ["impressions","affichages publicitaires","nombre d impressions"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Impressions", en: "Impressions" },
  },
  "marketing.conversions": {
    conceptId: "marketing.conversions",
    canonicalKey: "conversions",
    kind: "COUNT",
    criticality: "optional",
    domains: ["MARKETING"],
    dataType: "INTEGER",
    aggregation: "SUM",
    lexicon: ["conversions","nombre de conversions","nb conversions"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Conversions", en: "Conversions" },
  },
  "customer.lifetimeValue": {
    conceptId: "customer.lifetimeValue",
    canonicalKey: "lifetime_value",
    kind: "STOCK",
    criticality: "optional",
    domains: ["CLIENTS"],
    dataType: "CURRENCY",
    aggregation: "AVG",
    lexicon: ["valeur vie client","valeur a vie","ltv"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Valeur vie client", en: "Customer lifetime value" },
  },
  "customer.totalOrders": {
    conceptId: "customer.totalOrders",
    canonicalKey: "total_orders",
    kind: "COUNT",
    criticality: "optional",
    domains: ["CLIENTS"],
    dataType: "INTEGER",
    aggregation: "LAST",
    lexicon: ["nb commandes","total commandes"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Nombre de commandes", en: "Total orders" },
  },
  "hr.hourlyRate": {
    conceptId: "hr.hourlyRate",
    canonicalKey: "hourly_rate",
    kind: "RATE",
    criticality: "optional",
    domains: ["RH"],
    dataType: "CURRENCY",
    aggregation: "AVG",
    lexicon: ["taux horaire","salaire horaire","hourly rate","hourly wage"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Taux horaire", en: "Hourly rate" },
  },
  "hr.annualSalary": {
    conceptId: "hr.annualSalary",
    canonicalKey: "annual_salary",
    kind: "STOCK",
    criticality: "optional",
    domains: ["RH"],
    dataType: "CURRENCY",
    aggregation: "LAST",
    lexicon: ["salaire annuel","salaire de base annuel","salaire base annuel","annual salary","base salary"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Salaire annuel", en: "Annual salary" },
  },
  "inventory.reorder_point": {
    conceptId: "inventory.reorder_point",
    canonicalKey: "reorder_point",
    kind: "STOCK",
    criticality: "optional",
    domains: ["OPERATIONS"],
    dataType: "NUMBER",
    aggregation: "NONE",
    lexicon: ["seuil d alerte", "seuil d'alerte", "seuil alerte", "seuil de reapprovisionnement", "seuil reappro", "point de commande", "reorder point", "seuil_d_alerte"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Seuil d'alerte", en: "Reorder point" },
  },
  "marketing.budget": {
    conceptId: "marketing.budget",
    canonicalKey: "budget",
    kind: "FLOW",
    criticality: "optional",
    domains: ["MARKETING", "FINANCE"],
    dataType: "CURRENCY",
    aggregation: "SUM",
    lexicon: ["budget cad", "budget", "budget alloue", "budget total", "budget publicitaire", "budget_cad"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Budget marketing", en: "Marketing budget" },
  },
  "employee.role": {
    conceptId: "employee.role",
    canonicalKey: "role",
    kind: "COUNT",
    criticality: "optional",
    domains: ["RH"],
    dataType: "STRING",
    aggregation: "NONE",
    lexicon: ["role / poste", "role poste", "role", "poste", "fonction", "titre de poste", "titre", "role_poste"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Rôle / Poste", en: "Role / Position" },
  },
  "summary.orders": {
    conceptId: "summary.orders",
    canonicalKey: "total_orders",
    kind: "COUNT",
    criticality: "optional",
    domains: ["VENTES", "FINANCE"],
    dataType: "INTEGER",
    aggregation: "SUM",
    lexicon: ["nb transactions", "nombre de transactions", "nombre transactions", "transactions totales", "volume commandes", "nb_transactions", "nombre_transactions"],
    missingBehavior: "NOT_IMPORTED",
    label: { fr: "Nombre de transactions", en: "Total orders" },
  },
};

export const CATEGORIES: Record<string, CategoryDefinition> = {
  marketing_channel: {
    categoryId: "marketing_channel",
    canonicalValues: ["meta_ads", "google_ads", "instagram", "email", "tiktok", "shopify", "magasin", "web", "b2b"],
    lexicon: {
      meta_ads: ["facebook ads", "facebook", "fb ads", "fb", "meta ads", "meta"],
      google_ads: ["google ads", "adwords", "affichage", "affichage / web"],
      instagram: ["instagram", "instagram ads"],
      email: ["email", "courriel", "infolettre"],
      tiktok: ["tiktok", "tiktok ads"],
      shopify: ["shopify"],
      web: ["web", "boutique en ligne", "e-commerce", "web shopify/erp", "site web"],
      magasin: ["magasin", "boutique physique", "en personne", "magasin lévis", "magasin sainte-foy", "magasin chicoutimi"],
      b2b: ["b2b commercial", "b2b grossiste", "grands comptes", "institutionnel"],
    },
  },
  provinces: {
    categoryId: "provinces",
    canonicalValues: ["QC", "ON", "NB", "NS", "NL", "PE", "MB", "SK", "AB", "BC", "YT", "NT", "NU"],
    lexicon: {
      QC: ["qc", "quebec", "québec"],
      ON: ["on", "ontario"],
      NB: ["nb", "nouveau-brunswick", "new brunswick"],
      NS: ["ns", "nouvelle-ecosse", "nova scotia"],
      NL: ["nl", "terre-neuve", "newfoundland"],
      PE: ["pe", "ipe", "ile-du-prince-edouard", "prince edward island"],
      MB: ["mb", "manitoba"],
      SK: ["sk", "saskatchewan"],
      AB: ["ab", "alberta"],
      BC: ["bc", "cb", "colombie-britannique", "british columbia"],
      YT: ["yt", "yukon"],
      NT: ["nt", "territoires du nord-ouest", "northwest territories"],
      NU: ["nu", "nunavut"],
    },
  },
  union_status: {
    categoryId: "union_status",
    canonicalValues: ["syndiqué", "non syndiqué"],
    lexicon: {
      "syndiqué": ["syndique", "syndiqué", "oui", "yes", "unionized"],
      "non syndiqué": ["non syndique", "non syndiqué", "non", "no", "non-unionized"],
    },
  },
  customer_type: {
    categoryId: "customer_type",
    canonicalValues: ["particulier", "entreprise", "b2b", "b2g"],
    lexicon: {
      particulier: ["particulier (b2c)", "particulier", "b2c", "individu", "consommateur"],
      entreprise: ["entreprise", "pme", "corporatif"],
      b2b: ["b2b", "business"],
      b2g: ["institutionnel/gouvernemental (b2b/b2g)", "gouvernement", "b2g", "institutionnel", "institutionnel/gouvernemental"],
    },
  },
  dpa_classes: {
    categoryId: "dpa_classes",
    canonicalValues: ["classe 0", "classe 1", "classe 8", "classe 10", "classe 12", "classe 43.2", "classe 50"],
    lexicon: {
      "classe 0": ["0", "classe 0", "terrain non amortissable"],
      "classe 1": ["1", "classe 1", "catégorie 1", "bâtiment"],
      "classe 8": ["8", "classe 8", "catégorie 8", "équipement", "rayonnage"],
      "classe 10": ["10", "classe 10", "catégorie 10", "véhicule", "camion"],
      "classe 12": ["12", "classe 12", "catégorie 12", "logiciel"],
      "classe 43.2": ["43.2", "classe 43.2", "panneaux solaires", "énergie propre"],
      "classe 50": ["50", "classe 50", "catégorie 50", "serveurs", "ordinateurs", "robots"],
    },
  },
  payment_method: {
    categoryId: "payment_method",
    canonicalValues: ["carte_credit", "debit", "comptant", "virement_bancaire", "cheque", "eft", "financement"],
    lexicon: {
      carte_credit: ["carte de crédit", "carte de credit", "credit card", "visa", "mastercard", "amex"],
      debit: ["débit interac", "debit interac", "debit", "interac"],
      comptant: ["comptant", "cash", "especes"],
      virement_bancaire: ["virement bancaire net 30", "virement bancaire", "virement", "wire transfer", "net 30"],
      cheque: ["chèque d'entreprise", "cheque d'entreprise", "chèque", "cheque"],
      eft: ["transfert eft", "eft", "transfert électronique", "ach"],
      financement: ["financement accord d", "accord d", "financement", "paiement en plusieurs fois"],
    },
  },
};
